name: Prism.Plugin.Popups CI

on:
  push:
    branches: [ master ]
    paths:
      - "samples/**"
      - "src/**"
      - "tests/**"
      - "version.json"
      - "Prism.Plugin.Popups.sln"
      - ".github/workflows/ci.yml"
  workflow_dispatch:

jobs:
  build:
    uses: avantipoint/workflow-templates/.github/workflows/dotnet-build.yml@master
    with:
      name: Prism.Plugin.Popups
      solution-path: Prism.Plugin.Popups.sln
      dotnet-version: 7.0.x
      code-sign: true
    secrets:
      codeSignKeyVault: ${{ secrets.CodeSignKeyVault }}
      codeSignClientId: ${{ secrets.CodeSignClientId }}
      codeSignTenantId: ${{ secrets.CodeSignTenantId }}
      codeSignClientSecret: ${{ secrets.CodeSignClientSecret }}
      codeSignCertificate: ${{ secrets.CodeSignCertificate }}

  deploy-internal:
    uses: avantipoint/workflow-templates/.github/workflows/deploy-nuget.yml@master
    needs: build
    with:
      name: Deploy Internal
    secrets:
      feedUrl: ${{ secrets.IN_HOUSE_NUGET_FEED }}
      apiKey: ${{ secrets.IN_HOUSE_API_KEY }}

  deploy-sponsors:
    uses: avantipoint/workflow-templates/.github/workflows/deploy-nuget.yml@master
    needs: build
    with:
      name: Deploy Sponsor Connect
    secrets:
      feedUrl: ${{ secrets.SPONSOR_CONNECT_NUGET_FEED }}
      apiKey: ${{ secrets.SPONSOR_CONNECT_TOKEN }}
