name: Prism.Plugin.Popups PR Validation

on:
  pull_request:
    branches: [ master ]
    paths:
      - "samples/**"
      - "src/**"
      - "tests/**"
      - "version.json"
      - "Prism.Plugin.Popups.sln"
      - ".github/workflows/pr.yml"
  workflow_dispatch:

jobs:
  build:
    uses: avantipoint/workflow-templates/.github/workflows/msbuild-build.yml@master
    with:
      name: Prism.Plugin.Popups
      solution-path: Prism.Plugin.Popups.sln
      dotnet-version: 7.0.x
